"""Constants for the Logitech Z906 integration."""

DOMAIN = "logitech_z906"

CONF_REMOTE_ENTITY = "remote_entity"
CONF_POWER_SENSOR = "power_sensor"

# Device name used in Broadlink storage for IR codes
BROADLINK_DEVICE = "Logitech Z906"

# Power threshold in watts — above this = amplifier is on
POWER_THRESHOLD = 2

# IR commands as Broadlink base64 (NEC1 protocol, Device 2, SubDevice 160)
# Source: https://gist.github.com/azgooon/9b4b680dba600f1b003a33ab5f9a572c
IR_CODES = {
    "on": "JgBYAAABJJAUERU0FRAVDxQRFBEVDxUQFBEUERQQFRAUERQ1FBEUNRQRFBAVEBQRFBEUEBUQFDUVNBU1FDUUNRQ1FDUUNRUQFAAF2wABKEgUAAxNAAEqRRYADQU=",
    "off": "JgBYAAABJJAUERU0FRAVDxQRFBEVDxUQFBEUERQQFRAUERQ1FBEUNRQRFBAVEBQRFBEUEBUQFDUVNBU1FDUUNRQ1FDUUNRUQFAAF2wABKEgUAAxNAAEqRRYADQU=",
    "mute": "JgBQAAABI5EUERQ1FBEUERMRFBEUERQRFBAUERMSFBEUEBQ1FBEUNRQREzYUERQ1FBETNhM2FDUUNRQRFDUUERQ1FBETEhMRFAAF3AABKEcTAA0FAAAAAAAAAAA=",
    "volumeUp": "JgBQAAABIpIUERM2ExITEhMSExETEhMSExEUERMSExITERQ1FBETNhQRFDYTERM2ExITNhMSEzYTNhMSEzYTEhM2ExITNhMRFAAF3AABKEcVAA0FAAAAAAAAAAA=",
    "volumeDown": "JgBQAAABJY8WDxYzFg8WDhYPFg8WDxYOFg8WDxYOFg8WDxYzFg8WMxYPFjMWDxYzFg8WMxYzFg8WMxYOFjQWDhYzFg8WDxYzFgAF2QABKkYWAA0FAAAAAAAAAAA=",
    "input1": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxISEhISEhISEhISNxI3EhISNxI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "input2": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "input3": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxI3EhISEhISEhISNxI3EhISEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "input4": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxI3EhISEhISEjcSNxI3EhISEhI3EjcSNxISEgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "input5": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhISEhISNxISEjcSNxI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "aux": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhI3EhISNxISEjcSNxI3EjcSEhI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "effect": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSNxI3EhISEhISEhISNxISEhISEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "level": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "nextChannel": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
}

# Source name -> IR command key mapping
SOURCES = {
    "Input 1": "input1",
    "Input 2": "input2",
    "Input 3": "input3",
    "Input 4": "input4",
    "Input 5": "input5",
    "AUX": "aux",
}
